version: "3.7"

services:
  db:
    image: postgres
  web:
    build: ./
    ports:
      - "3000:8000"
    volumes:
      - .:/code
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db